name: Release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
        npm install -g electron-packager
        
    - name: Build Electron app
      run: npm run build

    - name: Download GitHub CLI (gh)
      run: |
        wget https://github.com/cli/cli/releases/latest/download/gh_linux_amd64.tar.gz
        tar xvf gh_linux_amd64.tar.gz
        sudo mv gh_* /usr/local/bin/gh

    - name: Create Release
      run: |
        gh release create v${{ github.ref }} ./dist/MonProjet-win32-x64/*.exe -n "Release notes"
